# Lesson End Project: Numpy Operations

### Problem statement: 

In this project, we will explore the powerful capabilities of the NumPy library for numerical analysis and perform various operations on arrays using its efficient functions. NumPy is a fundamental package for scientific computing with Python and provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays.

In order to complete the project, define an array and perform arithmetic, statistical, slicing, and indexing operations on it.

### Steps to be followed:

1. Array Creation and Manipulation
2. Array Operations
3. Statistical Analysis
4. Array Slicing and Indexing

### 1. Array Creation and Manipulation:
- Create a one-dimensional array of integers ranging from 1 to 10 using NumPy
- Reshape the array into a 2x5 matrix

In [4]:
import numpy as np

array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2d = array1d.reshape(2, 5)


print("1D Array:", array1d)
print("2D Array:\n", array2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
import numpy as np

array1d = np.arange(1,11)
array2d = array1d.reshape(5, 2)


print("1D Array:", array1d)
print("2D Array:\n", array2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### 2. Array Operations:
- Perform element-wise addition, subtraction, multiplication, and division on two arrays

In [4]:
a = np.array([1, 2, 3])
print(a*2)
b = np.array([4, 5, 6])
addition_result = a + b
subtraction_result = a - b
multiplication_result = a * b
division_result = a / b

print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

[2 4 6]
Addition Result: [5 7 9]
Subtraction Result: [-3 -3 -3]
Multiplication Result: [ 4 10 18]
Division Result: [0.25 0.4  0.5 ]


### 3. Statistical Analysis:
- Generate a random array of 100 numbers and calculate its mean, median, and standard deviation

In [6]:
random_array = np.random.rand(10)
print(random_array)
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

print("Mean Value:", mean_value)
print("Median Value:", median_value)
print("Standard Deviation:", std_deviation)

[0.34680489 0.04080143 0.77825319 0.0819784  0.75036714 0.96120101
 0.48785862 0.12366703 0.66888575 0.38619303]
Mean Value: 0.46260104883395403
Median Value: 0.4370258225369611
Standard Deviation: 0.30514759815526055


### 4. Array Slicing and Indexing:
- Extract a subset of elements from an array using slicing
- Change the values of specific elements in an array using indexing

In [ ]:
print("1D Array:", array1d)
print(array1d[1],array1d[-1])#indexing
print(array1d[1:])#slicing
print(array1d[:1])
print(array1d[:-1])

# objects in terms of programming means a data structure that can hold multiple values.
# Objects meaning the instance of a class, which is a blueprint for creating objects.

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2 10
[ 2  3  4  5  6  7  8  9 10]
[1]
[1 2 3 4 5 6 7 8 9]


In [12]:
print(array1d[:])
print(array1d[::2]) #striding
print(array1d[::3]) #striding
print(array1d[::-1]) #striding

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1  4  7 10]
[10  9  8  7  6  5  4  3  2  1]


In [8]:
sliced_array = array1d[2:6]
print("Sliced Array:", sliced_array)


Sliced Array: [3 4 5 6]


In [51]:
print("2D Array:\n", array2d)
array2d[1, 1] = 20
print("Modified 2D Array:\n", array2d)

2D Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Modified 2D Array:
 [[ 1  2]
 [ 3 20]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
