# __Attributes and Functions in Python__

https://numpy.org/doc/2.2/user/absolute_beginners.html

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- Attributes of NumPy Arrays
  * Explanation of Attributes
- NumPy Array Functions

## __1. Attributes of NumPy Arrays__ ##

Few common attributes of NumPy array:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_1.png)

In [25]:
# An example for each attribute is given below:
import numpy as np
arr = np.array([[ 1, 2, 3], [ 4,7, 5]])
print (arr)
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
print("Length of one array element in bytes. : ", arr.itemsize)
print("array’s data. : ", arr.data)

[[1 2 3]
 [4 7 5]]
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32
Length of one array element in bytes. :  4
array’s data. :  <memory at 0x00000251F0B39080>


In [27]:
arr = np.array([[ "cat", 2, 3], [ 4, 2.0, 5.8]])
print (arr)
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
print("Length of one array element in bytes. : ", arr.itemsize)
print("array’s data. : ", arr.data)

[['cat' '2' '3']
 ['4' '2.0' '5.8']]
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  <U32
Length of one array element in bytes. :  128
array’s data. :  <memory at 0x00000251F0B43920>


### __1.1 Explanation of Attributes:__ ###
- `ndarray.ndim`: It is the number of axes (dimensions) of the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_2.png)

- `ndarray.shape`: It provides the size of the array for each dimension. The output data type is a tuple.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_3.png)

- `ndarray.size` : It is the total number of elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_4.png)

- `ndarray.dtype`: It shows the data type of the elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_5.png)

- `ndarray.itemsize`: It shows the length of one array element in bytes.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/IMage_6.png)

- `ndarray.data`: It is an attribute offering direct access to the raw memory of a NumPy array.

## __2. NumPy Array Functions__ ##
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_7.png)

- `ndarray.reshape`: It is used to reshape (new shape) the current elements of an array.

In [11]:
# Example: Converting a 1D Array to a 2D Array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.ndim)
newarr = arr.reshape(3,2,2)
print (newarr)
print(newarr.ndim)

1
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [33]:
newarr = arr.reshape(2,6)
print (newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
newarr = arr.reshape(12,1)
print (newarr)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [37]:
newarr = arr.reshape(4,4)
print (newarr)

ValueError: cannot reshape array of size 12 into shape (4,4)

## flatten()

ndarray.flatten(order='C')

C’ means to flatten array elements into row-major order (C-style).

‘F’ means to flatten array elements into column-major order (Fortran-style).

‘A’ – means to flatten array elements in column-major order if a is Fortran contiguous in memory or row-major otherwise.

‘K’ means to flatten array elements in order of the elements laid out in memory.



In [23]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
b = a.flatten()
print(b)
c=a.flatten(order='F')
print(c)

[[1 2]
 [3 4]]
[1 2 3 4]
[1 3 2 4]


Note that b is a copy, not a view of the array a. If you change elements in array b, the elements in array a are not changed.

In [17]:
# change element at index 0
b[0] = 0
print(b)

# display the array a
print(a)

[0 2 3 4]
[[1 2]
 [3 4]]


- `ndarray.flatten`: It returns a copy of the array flattened into a 1D array.

In [25]:
# Converting a multidimensional(3D) array into a 1D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3D)
print(arr3D.ndim)
print(arr3D.shape)
flattened_array = arr3D.flatten(order='F')
print(flattened_array)
print(flattened_array.ndim)
print(flattened_array.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
[ 1  7  4 10  2  8  5 11  3  9  6 12]
1
(12,)


- `ndarray.transpose`: It swaps the rows and columns of a 2D array.

In [9]:
# Let's create a 2D array for the transpose example
var =[[1, 2, 3], [4, 5, 6]]
arr2D = np.array(var)
print(arr2D)
# Transposing the 2D array
transposed_array = arr2D.transpose()
print(transposed_array)
print(arr2D.shape , transposed_array.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3) (3, 2)


In [27]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.ndim)
newarr = arr.reshape(4,3,1)
print (newarr)

1
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [29]:
t=newarr.transpose()
print(t)
print(t.shape)

[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]]
(1, 3, 4)


## __Assisted Practice__

### __Problem Statement:__

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]


**Steps to Perform:**

1. Explore the key attributes of NumPy arrays, including `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`.
2. Demonstrate important NumPy array functions such as `reshape`, `flatten`, and `transpose`.

In [31]:
temperatures = np.array([ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ])
print(temperatures)
print("No. of dimensions: ", temperatures.ndim)
print("Shape of array: ", temperatures.shape)
print("Size of array: ", temperatures.size)
print("Array stores elements of type: ", temperatures.dtype)
print("Length of one array element in bytes. : ", temperatures.itemsize)
print("array’s data. : ", temperatures.data)
newarr = temperatures.reshape(7,1)
print (newarr)
flattened_array = temperatures.flatten()
print(flattened_array)
transposed_array = flattened_array.transpose()
print(transposed_array)

[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
No. of dimensions:  1
Shape of array:  (7,)
Size of array:  7
Array stores elements of type:  float64
Length of one array element in bytes. :  8
array’s data. :  <memory at 0x00000206ACE76EC0>
[[75.2]
 [77.1]
 [74.5]
 [79.3]
 [82.6]
 [81.2]
 [77.8]]
[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
