# __Introduction to NumPy__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

## __1. Fundamentals of NumPy__

https://numpy.org/doc/2.2/user/absolute_beginners.html

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [1]:
import numpy as np
arr = np.array ([30,40,50])
print (arr)
print (type(arr))
print (arr.ndim)
print (arr.shape)
print(len(arr))
print(arr.dtype)

[30 40 50]
<class 'numpy.ndarray'>
1
(3,)
3
int32


In [17]:
name=np.array("Simplilearn")
name

array('Simplilearn', dtype='<U11')

In [5]:
arr = np.array ([30,40,50,8.9,'cat'])
print (arr)

['30' '40' '50' '8.9' 'cat']


### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [11]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0) #scaler
print(arr0.ndim)
# Create a 1D Array
arr1 = np.array([1,2,3,4]) #vector
print ('1D array is', arr1)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]]) #matrix
print ('2D array is', arr2)
print(arr2.shape, arr2.ndim)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]) #nd array
print ('3D array is', arr3)
print(arr3.shape)

0D array is 24
0
1D array is [1 2 3 4]
2D array is [[1 1 1]
 [1 2 1]]
(2, 3) 2
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
(2, 2, 3)


**Observations:**
- 1D arrays are unidimensional and have 0D arrays as its elements.
- 2D arrays have 1D arrays as their elements.
- 3D arrays have 2D arrays as their elements.

## Array Vs List

In [13]:
import numpy as np
an_arr = np.arange(1000000)
a_list = list(range(1000000))
print(type(an_arr))
print(type(a_list))

<class 'numpy.ndarray'>
<class 'list'>


In [15]:
print(an_arr)


[     0      1      2 ... 999997 999998 999999]


In [15]:
print(a_list)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [17]:
%time for _ in range(10): an_arr2 = an_arr * 2

CPU times: total: 15.6 ms
Wall time: 30.7 ms


In [19]:
%time for _ in range(10): a_list2 = [x * 2 for x in a_list]
    

CPU times: total: 1.55 s
Wall time: 1.54 s
