#### Array Attributes

1. Arr.data
2. Arr.ndim
3. Arr.dtype
4. Arr.size
5. Arr.itemsize
6. Arr.shape



In [3]:
import numpy as np

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f'The array store at memory: ', arr.data)
print (f'The array is : {arr.ndim}d array')
print (f'The array type is :', arr.dtype)
print(f'The array shape is : ', arr.shape)
print (f'The array itemsize is : ', arr.itemsize)
print (f'The array sie is : ', arr.size)

The array store at memory:  <memory at 0x000001161DA70520>
The array is : 2d array
The array type is : int32
The array shape is :  (2, 4)
The array itemsize is :  4
The array sie is :  8


In [ ]:
arr = np.array([[1,'cat',3,4],[5,6.3,7.1,8]])
print(f'The array store at memory: ', arr.data) 
print (f'The array is : {arr.ndim}D array') #2D
print (f'The array type is :', arr.dtype) #<U32
print(f'The array shape is : ', arr.shape) # 2,4 
print (f'The array itemsize is : ', arr.itemsize) #4
print (f'The array sie is : ', arr.size) # 8

The array store at memory:  <memory at 0x000001161DA79080>
The array is : 2D array
The array type is : <U32
The array shape is :  (2, 4)
The array itemsize is :  128
The array sie is :  8


#### Functions of an array

1. Arr.reshape
2. Arr.transpose
3. Arr.flatten

In [17]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array = array.reshape(2,5)
print ('Shape of this array is : ',array.shape)
print (array)

Shape of this array is :  (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array = array.reshape(3,2,2)
print ('Shape of this array is : ',array.shape)
print (array)

Shape of this array is :  (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
