#### Array Attributes

1. Arr.data
2. Arr.ndim
3. Arr.dtype
4. Arr.size
5. Arr.itemsize
6. Arr.shape



In [2]:
import numpy as np

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f'The array store at memory: ', arr.data)
print (f'The array is : {arr.ndim}d array')
print (f'The array type is :', arr.dtype)
print(f'The array shape is : ', arr.shape)
print (f'The array itemsize is : ', arr.itemsize)
print (f'The array sie is : ', arr.size)

The array store at memory:  <memory at 0x000001161DA70520>
The array is : 2d array
The array type is : int32
The array shape is :  (2, 4)
The array itemsize is :  4
The array sie is :  8


In [ ]:
arr = np.array([[1,'cat',3,4],[5,6.3,7.1,8]])
print(f'The array store at memory: ', arr.data) 
print (f'The array is : {arr.ndim}D array') #2D
print (f'The array type is :', arr.dtype) #<U32
print(f'The array shape is : ', arr.shape) # 2,4 
print (f'The array itemsize is : ', arr.itemsize) #4
print (f'The array sie is : ', arr.size) # 8

The array store at memory:  <memory at 0x000001161DA79080>
The array is : 2D array
The array type is : <U32
The array shape is :  (2, 4)
The array itemsize is :  128
The array sie is :  8


#### Functions of an array

1. Arr.reshape
2. Arr.transpose
3. Arr.flatten
4. Arr.ravel

In [17]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array = array.reshape(2,5)
print ('Shape of this array is : ',array.shape)
print (array)

Shape of this array is :  (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array = array.reshape(3,2,2)
print ('Shape of this array is : ',array.shape)
print (array)

Shape of this array is :  (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [4]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array = array.ravel()
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### __Problem Statement:__

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]


**Steps to Perform:**

1. Explore the key attributes of NumPy arrays, including `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`.
2. Demonstrate important NumPy array functions such as `reshape`, `flatten`, and `transpose`.


In [25]:
import numpy as np
temperatures = np.array([ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ])

# Return the which Dimensional data 
print (np.ndim(temperatures),'D array')

# return the shpae
print ('Array shape is', np.shape(temperatures))

# return the size
print ('Array size is' , np.size(temperatures))

# return the datatype:
print ('Array contains data type', temperatures.dtype)

# return the array item size
print ('Array item size or total record', temperatures.itemsize)

# return the data in array 
print ('Array data ', temperatures.data)

1 D array
Array shape is (7,)
Array size is 7
Array contains data type float64
Array item size or total record 8
Array data  <memory at 0x00000268FE70F100>


In [42]:
# reshape the temperature 1D array to 2D

temperature_conv = temperatures.reshape(1,7)
print('Converted Array', temperature_conv.ndim, 'D')
print (temperature_conv)

Converted Array 2 D
[[75.2 77.1 74.5 79.3 82.6 81.2 77.8]]


In [43]:
# flatten will always return the multidimensional data to 1D
temperature_Flatten_array = temperature_conv.flatten()
temperature_Flatten_array


array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])

In [47]:
# transpose will covert row to col and col to row
temperature_transpose = temperature_conv.transpose()
temperature_transpose


array([[75.2],
       [77.1],
       [74.5],
       [79.3],
       [82.6],
       [81.2],
       [77.8]])

In [50]:
temperature_transpose.ravel() # same work as flatten

array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])