# slicing


- slicing of an array will denote as arrname[start:end:step]
- if start not mentioned the considered as 0
- if stop not mentioned then considered as len of array
- if step not mentioned then considered as 1


In [1]:
import numpy as np

In [2]:
# try to slice 1D array

arr1d = np.array([1,2,3,4,5,6,7,8,9])
arr1d[:3]

array([1, 2, 3])

In [3]:
# print the value from the 4th index to the last
arr1d[5:]

array([6, 7, 8, 9])

In [4]:
# slice using step
arr1d[::3]

array([1, 4, 7])

- In 2d array it consider [row,column]

In [12]:
# try to slice 2D array

arr2d = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr2d

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [13]:
arr2d[:] # all row all column

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [16]:
arr2d[1] # 1 index row array    

array([5, 4, 3, 2, 1])

In [20]:
arr2d[0,:2] # 0 the index row and column index start from 0 to 2

array([1, 2])

In [22]:
arr2d[0,:5:2] # 0 is the index row and column index start from 0 end at 5 and steps are 2

array([1, 3, 5])

In [53]:
arr2d[:,0:5:4]

array([[1, 5],
       [5, 1]])

- In 3d array also consider also same [row , depth, column]

In [41]:
arr3d = np.array([[[1,2,3,4,5],[5,4,3,2,1],[0,9,8,7,6]],[[11,22,33,44,55],[5,4,3,2,1],[0,9,8,7,6]]])
arr3d.ndim

3

In [42]:
arr3d

array([[[ 1,  2,  3,  4,  5],
        [ 5,  4,  3,  2,  1],
        [ 0,  9,  8,  7,  6]],

       [[11, 22, 33, 44, 55],
        [ 5,  4,  3,  2,  1],
        [ 0,  9,  8,  7,  6]]])

In [ ]:
# Here in every dimension start, stop and end will be applicable
arr3d[1,0,:3] # [row , depth, column]

array([11, 22, 33])

In [56]:
arr3d[:,:, 1:5:2] # here i picked the array as [all rows, all depth, column start from 1 , end at the len of array and the step is 2]

array([[[ 2,  4],
        [ 4,  2],
        [ 9,  7]],

       [[22, 44],
        [ 4,  2],
        [ 9,  7]]])

In [58]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]


### __Problem Statement:__

- Creating arrays for slicing:
  * Create a 1D NumPy array with at least 15 elements
  * Create a 2D NumPy array with a minimum of 4 rows and 5 columns
  * Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns

- Slicing 1D arrays:
  * Perform and demonstrate different slices on the 1D array, explore it using step values

- Slicing 2D arrays:
  * Slice rows and columns separately and in combination

- Slicing 3D arrays:
  * Perform slicing to access different matrices, rows within matrices, and elements within rows

- Negative slicing:
  * Implement negative slicing on 1D, 2D, and 3D arrays
  * Compare the outcomes of negative slicing with positive slicing

In [ ]:
# Q1 
array1d = np.arange(1,16)
array2d = np.array([[1,2,3,4,5],[5,4,3,2,1],[11,22,33,44,55],[55,44,33,22,11]])
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [96]:
print ('Array 1D\n\n',array1d)
print ('--'* 25)
print ('\nArray 2D\n\n',array2d)
print ('--'* 25)
print ('\nArray 3D\n\n',array3d)

Array 1D

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
--------------------------------------------------

Array 2D

 [[ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [11 22 33 44 55]
 [55 44 33 22 11]]
--------------------------------------------------

Array 3D

 [[[ 1  2  3  4  5]
  [ 5  4  3  2  1]
  [ 0  9  8  7  6]]

 [[11 22 33 44 55]
  [55 44 33 22 11]
  [ 0 99 88 77 66]]]


In [101]:
# slicing techniques apply on the 1d array

# 1st 5 elements
print ('1st 5 elements',array1d[:5])
# last 5 elements
print ('Last 5 elements',array1d[-5:])
# every 2nd elements
print ('Every second elements', array1d[::2])

1st 5 elements [1 2 3 4 5]
Last 5 elements [11 12 13 14 15]
Every second elements [ 1  3  5  7  9 11 13 15]
