# __Indexing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Indexing
  * Access Elements in the 1D NumPy Array
  * Access Elements in the 2D NumPy Array
  * Access Elements in 3D NumPy Array
  * Negative Indexing

## __1. NumPy Array Indexing__ ##
NumPy indexing allows you to access an array element using an index value, which begins from 0.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [2]:
# Let's create 1D, 2D and 3D NumPy arrays:
import numpy as np
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

### __1.1 Access Elements in the 1D NumPy Array__ ###

In [14]:
print(array_1d)
print(array_1d.shape)
print(array_1d[-1])

[1 2 3 4 5 6]
(6,)
6


In [8]:
print(array_2d)
print(array_2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
print(array_3d)
print(array_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [13]:
print(array_3d[1,1,1])

11


In [16]:
print(array_1d)
# Print the value of index 3
print(array_1d[3])

[1 2 3 4 5 6]
4


In [15]:
# Print the addition of indexes 0 and 1
print(array_1d[1] + array_1d[0])

3


### __1.2 Access Elements in the 2D NumPy Array__
Consider a 2D array as a table, with dimensions as rows and indexes as columns.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [18]:
print(array_2d)
# Print third element of the first row of a 2D array
print('3rd element on 1st row: ', array_2d[0, 2])

[[1 2 3]
 [4 5 6]]
3rd element on 1st row:  3


In [3]:
import numpy as np
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [20]:
# Print second element of the second row of a 2D array
print('2nd element on 2nd row: ', array_2d[1, 1])

2nd element on 2nd row:  5


### __1.3 Access Elements in 3D NumPy Array__ ###
- [x,y,z] corresponds to xth element, yth row, and zth column.

In [7]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d)
# Print the first element of the second array
print(array_3d[1, 1, 0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
10


### __1.4 Negative Indexing__

- Negative indices are counted from the end of an array.
- In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [11]:
 # Print the fourth element of the 1D array using negative indexing
array_1d = np.array([1,2,3,4,5,6])
print(array_1d[-3])

4


In [20]:
print(array_2d)
# Print the last element of the 2D array using negative indexing
print(array_2d[1,-1])

[[1 2 3]
 [4 5 6]]
6


In [15]:
# Print the last element of the 3D array using negative indexing
print(array_3d)
print(array_3d[1,1,-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


## __Assisted Practice__

### __Problem Statement:__

1. Create a 1D NumPy array with at least 10 elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
   
Accessing Elements in Arrays

5. Access and print various elements from 1D, 2D, and, 3D using positive indexing
6. Access and print elements using negative indices in all three arrays
7. Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays


In [19]:
a = np.arange(1,100,10)
a

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
import numpy as np
a=np.random.rand(3,4)
a

array([[0.59146898, 0.45103656, 0.49584406, 0.65791624],
       [0.41584366, 0.25244528, 0.15717719, 0.75455227],
       [0.12568803, 0.33360143, 0.52306225, 0.341474  ]])

In [29]:
arr=np.zeros([3,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr=np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
b = np.arange(12)
c= b.reshape(2,2,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [37]:
c[1,1,1]

10

In [39]:
c[-1,-1,-1]

11

In [47]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
print(b)
print(b[2,2],c[1,1,2])
sum = np.add(b[2,2],c[1,1,2])
print (sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11 11
22


In [65]:
a = np.array([[1,2,1,4],[1,2,2,3]])
print(a)
b = np.array([[1,3,1,1], [1,1,1,1]])
print(b)

result = np.divide (b,a)
print(result)

[[1 2 1 4]
 [1 2 2 3]]
[[1 3 1 1]
 [1 1 1 1]]
[[1.         1.5        1.         0.25      ]
 [1.         0.5        0.5        0.33333333]]
