In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array(range(1,11))
print (arr1)
print (arr2)

# Reshape the array to 2D
arr1_reshaped = arr1.reshape(2, 5)
print (arr1_reshaped)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# addition and subtraction
# multiplication and division
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array(range(1,11))
print (arr1+arr2)
print (arr1-arr2)
print (arr1*arr2)   
print (arr1/arr2)

[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
