# __Slicing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Slicing
  * Slicing 1D NumPy Arrays
  * Slicing Using Step Value
  * Slicing: 2D Array
  * Slicing: 3D Array
  * Negative Slicing

## __1. NumPy Array Slicing__

- In Python, slicing refers to moving elements from one index to another.
- Instead of using an index, the slice is passed as **[start:end]**.
- Another way to pass the slice is to add a step as **[start:end:step]**.
- In slicing, if the starting is not passed, it is considered as 0. If the step is not passed as 1 and if the end is not passed, it is considered as the length of the array in that dimension.

### __1.1 Slicing 1D NumPy Arrays__

#### Example 1: Use slicing to retrieve employee ratings for a team of seven employees in the first quarter from an array

In [5]:
import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9])
print(Employee_rating[:3])

[1 4 3]


#### Example 2: Print the list of three subjects from the fourth index to the end

In [9]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[-3:])
print(Books[5:])

['OPPs' 'Java' 'Cloud']
['OPPs' 'Java' 'Cloud']


### __1.2 Slicing Using Step Value__

In [11]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X)
print(X[1:6])
print(X[1:6:2])

[8 7 6 5 4 3 2 1]
[7 6 5 4 3]
[7 5 3]


### __1.3 Slicing: 2D Array__

In [8]:
Z = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 110]])
print(Z)
print(Z[0, 2:3])

[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
[33]


### __1.4 Slicing: 3D Array__

In [10]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d)
print(array_3d[0,1:,1:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[5 6]]


### __1.5 Negative Slicing__
- Negative slicing is the same as negative indexing, which is interpreted as counting from the end of an array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/5_Slicing/Image_1.png)

In [12]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]


## __Assisted Practice__

### __Problem Statement:__

- Creating arrays for slicing:
  * Create a 1D NumPy array with at least 15 elements
  * Create a 2D NumPy array with a minimum of 4 rows and 5 columns
  * Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns

- Slicing 1D arrays:
  * Perform and demonstrate different slices on the 1D array, explore it using step values

- Slicing 2D arrays:
  * Slice rows and columns separately and in combination

- Slicing 3D arrays:
  * Perform slicing to access different matrices, rows within matrices, and elements within rows

- Negative slicing:
  * Implement negative slicing on 1D, 2D, and 3D arrays
  * Compare the outcomes of negative slicing with positive slicing

In [16]:
array_1d = np.arange(1, 16)
print(array_1d)
# Slicing 1D Array
print("\nSlicing 1D Array:")
print("-------------------------")
print("First 5 elements:", array_1d[:5])
print("-------------------------")
print("Last 5 elements:", array_1d[-5:])
print("-------------------------")
print("Every 2nd element:", array_1d[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Slicing 1D Array:
-------------------------
First 5 elements: [1 2 3 4 5]
-------------------------
Last 5 elements: [11 12 13 14 15]
-------------------------
Every 2nd element: [ 1  3  5  7  9 11 13 15]


In [18]:
arr1D = np.arange(1,30,2)
arr2D = np.array([[1,2,3,4,5],[5,2,6,7,8],[8,1,2,3,4],[0,4,2,6,7]])
arr3D = np.array([[[1,2,3,4],[5,2,6,7],[8,1,2,3]],[[0,4,2,6],[5,1,2,3],[3,4,2,6]]])

In [22]:
#Slicing in 3Dimentional Array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(arr[1:2,1:2,:])# [13,14,15]
print(arr[:,1:3,1:3])# [5,6][8,9] [14,15][17,18] [23,24][26,27]
print(arr[::2,::2,::2])# [1,3][7,9]  [19,21][25,17]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[13 14 15]]]
[[[ 5  6]
  [ 8  9]]

 [[14 15]
  [17 18]]

 [[23 24]
  [26 27]]]
[[[ 1  3]
  [ 7  9]]

 [[19 21]
  [25 27]]]
